//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string LastLoginIp { get; set; }
        public bool IsActivated { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime LastLockedOutDate { get; set; }
        public string LastLockedOutReason { get; set; }
        public string NewPasswordKey { get; set; }
        public Nullable<System.DateTime> NewPasswordRequested { get; set; }
        public string NewEmail { get; set; }
        public string NewEmailKey { get; set; }
        public Nullable<System.DateTime> NewEmailRequested { get; set; }
    }
}
